title: Ana Simões, Designer
author: Ana Simões
email: anaraquelsimoes97@gmail.com
description: > # this means to ignore newlines until "exclude"
  Hello, my name is Ana and this is my portfolio. Enjoy.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

